run_name: "standard_run_"

# Env params
max_program_len_factor: 9
max_exec_cost_factor: 18
start_data_len: 7                   # toTest
max_data_len: 7
verbosity: 0
do_action_masking: true             # toTest


# Train params
total_timesteps: 1_000_000
gradient_save_freq: 100
batch_size: 256                     # toTrain
model_checkpoint: null #"models/ohfmwinz/model.zip" # str | null

temperature: 2.0                    # toTrain
entropy_coefficient: 0.1            # toTrain

# Callback params
grow_data: false                    # toTest
delta: 0.01
patience: 2
eval_interval: 10_000

# Model params
pretrained_encoder: "pretrained" # choose from ["jina-pretrained", "jina-not-pretrained", "default"]        # toTest

# Debug params
offline: false
debug: false
