method: bayes  # or 'random' or 'grid'
metric:
  name: ep_rew_mean
  goal: maximize

parameters:
  entropy-coefficient:
    distribution: uniform
    min: 0.0
    max: 0.5

command:
  - poetry
  - run
  - python3
  - rlad_bst/train.py
  - --config=config.yaml
  - ${args}
