method: grid  # or 'random' or 'bayes'
metric:
  name: rollout/ep_rew_mean
  goal: maximize

parameters:
  batch-size:
    values: [64, 256, 1024] 
  learning-rate:
    values: [0.003, 0.0003, 0.00003]
  temperature:
    values: [1.0, 2.0, 10.0]
  entropy-coefficient:
    values: [0.0, 0.1, 0.5]

command:
  - poetry
  - run
  - python3
  - rlad_bst/train.py
  - --config=config.yaml
  - ${args}
